/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An enum of the Character\'s species   1: Human   2: Alien   3: Animal   
 * @export
 * @enum {string}
 */

export const CharacterSpeciesEnum = {
    /**
    * human
    */
    Human: 1,
    /**
    * alien
    */
    Alien: 2,
    /**
    * animal
    */
    Animal: 3
} as const;

export type CharacterSpeciesEnum = typeof CharacterSpeciesEnum[keyof typeof CharacterSpeciesEnum];



