/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An enum of the date format   1: official   2: wikia   3: wikipedia   4: facebook   5: twitter   6: twitch   8: instagram   9: youtube   10: iphone   11: ipad   12: android   13: steam   14: reddit   15: itch   16: epicgames   17: gog   18: discord   
 * @export
 * @enum {string}
 */

export const CompanyWebsiteEnums = {
    /**
    * official
    */
    official: 1,
    /**
    * wikia
    */
    wikia: 2,
    /**
    * wikipedia
    */
    wikipedia: 3,
    /**
    * facebook
    */
    facebook: 4,
    /**
    * twitter
    */
    twitter: 5,
    /**
    * twitch
    */
    twitch: 6,
    /**
    * instagram
    */
    instagram: 8,
    /**
    * youtube
    */
    youtube: 9,
    /**
    * iphone
    */
    iphone: 10,
    /**
    * ipad
    */
    ipad: 11,
    /**
    * android
    */
    android: 12,
    /**
    * steam
    */
    steam: 13,
    /**
    * reddit
    */
    reddit: 14,
    /**
    * itch
    */
    itch: 15,
    /**
    * epicgames
    */
    epicgames: 16,
    /**
    * gog
    */
    gog: 17,
    /**
    * discord
    */
    discord: 18
} as const;

export type CompanyWebsiteEnums = typeof CompanyWebsiteEnums[keyof typeof CompanyWebsiteEnums];



