/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The external platform the game is on   1: steam   5: gog   10: youtube   11: microsoft   13: apple   14: twitch   15: android   20: amazon_asin   22: amazon_luna   23: amazon_adg   26: epic_game_store   28: oculus   29: utomik   30: itch_io   31: xbox_marketplace   32: kartridge   36: playstation_store_us   37: focus_entertainment   54: xbox_game_pass_ultimate_cloud   55: gamejolt   
 * @export
 * @enum {string}
 */

export const ExternalGameCategoryEnums = {
    /**
    * steam
    */
    steam: 1,
    /**
    * gog
    */
    gog: 5,
    /**
    * youtube
    */
    youtube: 10,
    /**
    * microsoft
    */
    microsoft: 11,
    /**
    * apple
    */
    apple: 13,
    /**
    * twitch
    */
    twitch: 14,
    /**
    * android
    */
    android: 15,
    /**
    * amazon_asin
    */
    amazon_asin: 20,
    /**
    * amazon_luna
    */
    amazon_luna: 22,
    /**
    * amazon_adg
    */
    amazon_adg: 23,
    /**
    * epic_game_store
    */
    epic_game_store: 26,
    /**
    * oculus
    */
    oculus: 28,
    /**
    * utomik
    */
    utomik: 29,
    /**
    * itch_io
    */
    itch_io: 30,
    /**
    * xbox_marketplace
    */
    xbox_marketplace: 31,
    /**
    * kartridge
    */
    kartridge: 32,
    /**
    * playstation_store_us
    */
    playstation_store_us: 36,
    /**
    * focus_entertainment
    */
    focus_entertainment: 37,
    /**
    * xbox_game_pass_ultimate_cloud
    */
    xbox_game_pass_ultimate_cloud: 54,
    /**
    * gamejolt
    */
    gamejolt: 55
} as const;

export type ExternalGameCategoryEnums = typeof ExternalGameCategoryEnums[keyof typeof ExternalGameCategoryEnums];



