/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The data type of feature description   0: boolean   1: description   
 * @export
 * @enum {string}
 */

export const GameVersionFeatureCategoryEnums = {
    /**
    * boolean
    */
    boolean: 0,
    /**
    * description
    */
    description: 1
} as const;

export type GameVersionFeatureCategoryEnums = typeof GameVersionFeatureCategoryEnums[keyof typeof GameVersionFeatureCategoryEnums];



