/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The value of this feature   0: NOT_INCLUDED   1: INCLUDED   2: PRE_ORDER_ONLY   
 * @export
 * @enum {string}
 */

export const GameVersionIncludedFeatureEnums = {
    /**
    * not_included
    */
    not_included: 0,
    /**
    * included
    */
    included: 1,
    /**
    * pre_order_only
    */
    pre_order_only: 2
} as const;

export type GameVersionIncludedFeatureEnums = typeof GameVersionIncludedFeatureEnums[keyof typeof GameVersionIncludedFeatureEnums];



