/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A game\'s category/catagories   0: main_game   1: dlc_addon   2: expansion   3: bundle   4: standalone_expansion   5: mod   6: episode   7: season   8: remake   9: remaster   10: expanded_game   11: port   12: fork   13: pack   14: update   
 * @export
 * @enum {string}
 */

export const GameCategoryEnums = {
    /**
    * main_game
    */
    main_game: 0,
    /**
    * dlc_addon
    */
    dlc_addon: 1,
    /**
    * expansion
    */
    expansion: 2,
    /**
    * bundle
    */
    bundle: 3,
    /**
    * standalone_expansion
    */
    standalone_expansion: 4,
    /**
    * mod
    */
    mod: 5,
    /**
    * episode
    */
    episode: 6,
    /**
    * season
    */
    season: 7,
    /**
    * remake
    */
    remake: 8,
    /**
    * remaster
    */
    remaster: 9,
    /**
    * expanded_game
    */
    expanded_game: 10,
    /**
    * port
    */
    port: 11,
    /**
    * fork
    */
    fork: 12,
    /**
    * pack
    */
    pack: 13,
    /**
    * update
    */
    update: 14
} as const;

export type GameCategoryEnums = typeof GameCategoryEnums[keyof typeof GameCategoryEnums];



