/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An enum of the region for the release date   1: europe   2: north_america   3: australia   4: new_zealand   5: japan   6: china   7: asia   8: worldwide   9: korea   10: brazil   
 * @export
 * @enum {string}
 */

export const PlatformVersionReleaseDateRegionEnum = {
    /**
    * europe
    */
    europe: 1,
    /**
    * north_america
    */
    north_america: 2,
    /**
    * australia
    */
    australia: 3,
    /**
    * new_zealand
    */
    new_zealand: 4,
    /**
    * japan
    */
    japan: 5,
    /**
    * china
    */
    china: 6,
    /**
    * asia
    */
    asia: 7,
    /**
    * worldwide
    */
    worldwide: 8,
    /**
    * korea
    */
    korea: 9,
    /**
    * brazil
    */
    brazil: 10
} as const;

export type PlatformVersionReleaseDateRegionEnum = typeof PlatformVersionReleaseDateRegionEnum[keyof typeof PlatformVersionReleaseDateRegionEnum];



