/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The category of the platform   1: console   2: arcade   3: platform   4: operating_system   5: portable_console   6: computer   
 * @export
 * @enum {string}
 */

export const PlatformCategoryEnums = {
    /**
    * console
    */
    console: 1,
    /**
    * arcade
    */
    arcade: 2,
    /**
    * platform
    */
    platform: 3,
    /**
    * operating_system
    */
    operating_system: 4,
    /**
    * portable_console
    */
    portable_console: 5,
    /**
    * computer
    */
    computer: 6
} as const;

export type PlatformCategoryEnums = typeof PlatformCategoryEnums[keyof typeof PlatformCategoryEnums];



