version: 2
updates:
  # Update all package ecosystems
  # We may want to add additional ecosystems and probably test running this on root since we have workspaces enabled
  - package-ecosystem: "npm"
    directory: "landing/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "frontend/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "backend/"
    schedule:
      interval: "daily"
