version: "3.8"
services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: g4mr
      POSTGRES_PASSWORD: g4mr
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
