import { bigint, pgEnum, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

export const AgeRatingCategoryPGEnum = pgEnum('CategoryEnum', [
  '',
  'ESRB',
  'PEGI',
  'CERO',
  'USK',
  'GRAC',
  'CLASS_IND',
  'ACB',
]);

export const RatingPGEnum = pgEnum('RatingEnum', [
  '',
  'Seven',
  'Twelve',
  'Sixteen',
  'Eighteen',
  'RP',
  'EC',
  'E',
  'E10',
  'T0',
  'M1',
  'AO2',
  'CERO_A3',
  'CERO_B4',
  'CERO_C5',
  'CERO_D6',
  'CERO_Z7',
  'USK_08',
  'USK_69',
  'USK_120',
  'USK_161',
  'USK_182',
  'GRAC_ALL3',
  'GRAC_Twelve4',
  'GRAC_Fifteen5',
  'GRAC_Eighteen6',
  'GRAC_TESTING7',
  'CLASS_IND_L8',
  'CLASS_IND_Ten9',
  'CLASS_IND_Twelve0',
  'CLASS_IND_Fourteen1',
  'CLASS_IND_Sixteen2',
  'CLASS_IND_Eighteen3',
  'ACB_G4',
  'ACB_PG5',
  'ACB_M6',
  'ACB_MA157',
  'ACB_R188',
  'ACB_RC9',
]);

export const ageRatingsTable = pgTable('ageRatings', {
  category: AgeRatingCategoryPGEnum('category'),
  checksum: text('checksum'),
  createdAt: timestamp('created_at').notNull().defaultNow(),
  igdbId: bigint('igdb_id', { mode: 'number' }).primaryKey(),
  rating: RatingPGEnum('rating'),
  ratingCoverUrl: text('url'),
  synopsis: text('synopsis'),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export type AgeRating = typeof ageRatingsTable.$inferInsert;
