import {
  integer,
  pgEnum,
  pgTable,
  serial,
  text,
  timestamp,
  bigint,
  uniqueIndex,
  index,
} from 'drizzle-orm/pg-core';
import { gamesTable } from './games';

export const ExternalGameCategoryPGEnum = pgEnum('ExternalGameCategoryEnum', [
  '',
  'steam',
  '',
  '',
  '',
  'gog',
  '',
  '',
  '',
  '',
  'youtube',
  'microsoft',
  '',
  'apple',
  'twitch',
  'android',
  '',
  '',
  '',
  '',
  'amazon_asin',
  '',
  'amazon_luna',
  'amazon_adg',
  '',
  '',
  'epic_game_store',
  '',
  'oculus',
  'utomik',
  'itch_io',
  'xbox_marketplace',
  'kartridge',
  '',
  '',
  '',
  'playstation_store_us',
  'focus_entertainment',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'xbox_game_pass_ultimate_cloud',
  'gamejolt',
]);

export const ExternalGameMediaPGEnum = pgEnum('ExternalGameMediaEnum', [
  '',
  'DIGITAL',
  'PHYSICAL',
]);

export const externalGamesTable = pgTable(
  'externalGames',
  {
    checksum: text('checksum'),
    createdAt: timestamp('created_at').notNull().defaultNow(),
    id: serial('game_id').notNull().unique(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    igdbId: bigint('igdb_id', { mode: 'number' }).primaryKey(),
    category: ExternalGameCategoryPGEnum('category'),
    countries: integer('countries').array(),
    igdbCreatedAt: timestamp('igdb_created_at'),
    game: bigint('game', { mode: 'number' }).references(
      () => gamesTable.igdbId,
    ),
    media: ExternalGameMediaPGEnum('media'),
    name: text('name'),
    platform: bigint('platform', { mode: 'number' }), //TODO: Add reference once platformTable is added
    uid: text('uid'),
    igdbUpdatedAt: timestamp('igdb_updated_at'),
    url: text('url'),
    year: integer('year'),
  },
  (table) => {
    return {
      igdbUidIdx: index('igdb_uid_idx').on(table.uid),
      uniqueUrlIdx: uniqueIndex('url_idx').on(table.url),
    };
  },
);
