/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AgeRatingContentDescriptionCategory } from '../enums/descriptor/AgeRatingContentDescriptionCategory';

/**
 *
 * @export
 * @interface AgeRatingContentDescription
 */
export interface AgeRatingContentDescription {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof AgeRatingContentDescription
   */
  id?: number;
  /**
   *
   * @type {AgeRatingContentDescriptionCategoryEnums}
   * @memberof AgeRatingContentDescription
   */
  category?: AgeRatingContentDescriptionCategory;
  /**
   * A string containing the age rating content descriptions
   * @type {string}
   * @memberof AgeRatingContentDescription
   */
  description?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof AgeRatingContentDescription
   */
  checksum?: string;
}
