/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The organization that has issued a specific rating   1: ESRB   2: PEGI   3: CERO   4: USK   5: GRAC   6: CLASS_IND   7: ACB
 */
export type AgeRatingCategoryEnums = 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const AgeRatingCategoryEnums = {
  ACB: 7 as AgeRatingCategoryEnums,
  CERO: 3 as AgeRatingCategoryEnums,
  CLASS_IND: 6 as AgeRatingCategoryEnums,
  ESRB: 1 as AgeRatingCategoryEnums,
  GRAC: 5 as AgeRatingCategoryEnums,
  PEGI: 2 as AgeRatingCategoryEnums,
  USK: 4 as AgeRatingCategoryEnums,
};
