/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The age rating assigned by the organization   1: Three   2: Seven   3: Twelve   4: Sixteen   5: Eighteen   6: RP   7: EC   8: E   9: E10   10: T   11: M   12: AO   13: CERO_A   14: CERO_B   15: CERO_C   16: CERO_D   17: CERO_Z   18: USK_0   19: USK_6   20: USK_12   21: USK_16   22: USK_18   23: GRAC_ALL   24: GRAC_Twelve   25: GRAC_Fifteen   26: GRAC_Eighteen   27: GRAC_TESTING   28: CLASS_IND_L   29: CLASS_IND_Ten   30: CLASS_IND_Twelve   31: CLASS_IND_Fourteen   32: CLASS_IND_Sixteen   33: CLASS_IND_Eighteen   34: ACB_G   35: ACB_PG   36: ACB_M   37: ACB_MA15   38: ACB_R18   39: ACB_RC
 */
export type AgeRatingEnums =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20
  | 21
  | 22
  | 23
  | 24
  | 25
  | 26
  | 27
  | 28
  | 29
  | 30
  | 31
  | 32
  | 33
  | 34
  | 35
  | 36
  | 37
  | 38
  | 39;

export const AgeRatingEnums = {
  ACB_G: 34 as AgeRatingEnums,
  ACB_M: 36 as AgeRatingEnums,
  ACB_MA15: 37 as AgeRatingEnums,
  ACB_PG: 35 as AgeRatingEnums,
  ACB_R18: 38 as AgeRatingEnums,
  ACB_RC: 39 as AgeRatingEnums,
  AO: 12 as AgeRatingEnums,
  CERO_A: 13 as AgeRatingEnums,
  CERO_B: 14 as AgeRatingEnums,
  CERO_C: 15 as AgeRatingEnums,
  CERO_D: 16 as AgeRatingEnums,
  CERO_Z: 17 as AgeRatingEnums,
  CLASS_IND_Eighteen: 33 as AgeRatingEnums,
  CLASS_IND_Fourteen: 31 as AgeRatingEnums,
  CLASS_IND_L: 28 as AgeRatingEnums,
  CLASS_IND_Sixteen: 32 as AgeRatingEnums,
  CLASS_IND_Ten: 29 as AgeRatingEnums,
  CLASS_IND_Twelve: 30 as AgeRatingEnums,
  E: 8 as AgeRatingEnums,
  E10: 9 as AgeRatingEnums,
  EC: 7 as AgeRatingEnums,
  Eighteen: 5 as AgeRatingEnums,
  GRAC_ALL: 23 as AgeRatingEnums,
  GRAC_Eighteen: 26 as AgeRatingEnums,
  GRAC_Fifteen: 25 as AgeRatingEnums,
  GRAC_TESTING: 27 as AgeRatingEnums,
  GRAC_Twelve: 24 as AgeRatingEnums,
  M: 11 as AgeRatingEnums,
  RP: 6 as AgeRatingEnums,
  Seven: 2 as AgeRatingEnums,
  Sixteen: 4 as AgeRatingEnums,
  T: 10 as AgeRatingEnums,
  Three: 1 as AgeRatingEnums,
  Twelve: 3 as AgeRatingEnums,
  USK_0: 18 as AgeRatingEnums,
  USK_6: 19 as AgeRatingEnums,
  USK_12: 20 as AgeRatingEnums,
  USK_16: 21 as AgeRatingEnums,
  USK_18: 22 as AgeRatingEnums,
};
