/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An Enum of the character\'s gender   0: Male   1: Female   2: Other
 */
export type CharacterGenderEnum = 0 | 1 | 2;

export const CharacterGenderEnum = {
  Female: 1 as CharacterGenderEnum,
  Male: 0 as CharacterGenderEnum,
  Other: 2 as CharacterGenderEnum,
};
