/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CharacterGenderEnum } from './characterGenderEnum';
import { CharacterSpeciesEnum } from './characterSpeciesEnum';

/**
 * Video game characters
 */
export interface Character {
  /**
   * Alternative names for a character
   */
  akas?: Array<string>;
  /**
   * The IGDB object unique identifier
   */
  character_gender?: number;
  /**
   * The IGDB object unique identifier
   */
  character_species?: number;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * A Character\'s country of origin
   */
  country_name?: string;
  /**
   * Date this was initally added to the IGDB database
   */
  created_at?: number;
  /**
   * Text describing a character
   */
  description?: string;
  games?: Array<number>;
  gender?: CharacterGenderEnum;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   */
  mug_shot?: number;
  /**
   * The character\'s name
   */
  name?: string;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  species?: CharacterSpeciesEnum;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
}
export namespace Character {}
