/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { CharacterGenderEnum } from '../enums/CharacterGenderEnum';
// May contain unused imports in some cases
// @ts-ignore
import { CharacterSpeciesEnum } from '../enums/CharacterSpeciesEnum';

/**
 * Video game characters
 * @export
 * @interface CharacterDTO
 */
export interface CharacterDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CharacterDTO
   */
  id?: number;
  /**
   * Alternative names for a character
   * @type {Array<string>}
   * @memberof CharacterDTO
   */
  akas?: Array<string>;
  /**
   * A CharacterDTO\'s country of origin
   * @type {string}
   * @memberof CharacterDTO
   */
  country_name?: string;
  /**
   * Date this was initally added to the IGDB database
   * @type {number}
   * @memberof CharacterDTO
   */
  created_at?: number;
  /**
   * Text describing a character
   * @type {string}
   * @memberof CharacterDTO
   */
  description?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof CharacterDTO
   */
  games?: Array<number>;
  /**
   *
   * @type {CharacterGenderEnum}
   * @memberof CharacterDTO
   */
  gender?: CharacterGenderEnum;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CharacterDTO
   */
  mug_shot?: number;
  /**
   * The character\'s name
   * @type {string}
   * @memberof CharacterDTO
   */
  name?: string;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof CharacterDTO
   */
  slug?: string;
  /**
   *
   * @type {CharacterSpeciesEnum}
   * @memberof CharacterDTO
   */
  species?: CharacterSpeciesEnum;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof CharacterDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof CharacterDTO
   */
  url?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof CharacterDTO
   */
  checksum?: string;
}
