/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Enums for collection membership type
 * @export
 * @interface CollectionTypeDTO
 */
export interface CollectionType {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CollectionType
   */
  id?: number;
  /**
   * The membership type name
   * @type {string}
   * @memberof CollectionType
   */
  name?: string;
  /**
   * Description of the membership type
   * @type {string}
   * @memberof CollectionType
   */
  description?: string;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof CollectionType
   */
  updated_at?: number;
  /**
   * Date this was initally added to the IGDB database
   * @type {number}
   * @memberof CollectionType
   */
  created_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof CollectionType
   */
  checksum?: string;
}
