/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The logos of developers and publishers
 * @export
 * @interface CompanyLogoDTO
 */
export interface CompanyLogoDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CompanyLogoDTO
   */
  id?: number;
  /**
   *
   * @type {boolean}
   * @memberof CompanyLogoDTO
   */
  alpha_channel?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof CompanyLogoDTO
   */
  animated?: boolean;
  /**
   * The height of the image in pixels
   * @type {number}
   * @memberof CompanyLogoDTO
   */
  height?: number;
  /**
   * The ID of the image used to construct an IGDB image link
   * @type {string}
   * @memberof CompanyLogoDTO
   */
  image_id?: string;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof CompanyLogoDTO
   */
  url?: string;
  /**
   * The width of the image in pixels
   * @type {number}
   * @memberof CompanyLogoDTO
   */
  width?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof CompanyLogoDTO
   */
  checksum?: string;
}
