/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChangeDateCategoryEnum } from './changeDateCategoryEnum';
import { StartDateCategoryEnum } from './startDateCategoryEnum';

/**
 * Video game companies, both publishers and developers
 */
export interface CompanyDTO {
  /**
   * The date when a compnay got a new ID
   */
  change_date?: number;
  change_date_category?: ChangeDateCategoryEnum;
  /**
   * The IGDB object unique identifier
   */
  change_date_format?: number;
  /**
   * The new ID for a company that has gone through a merger or restructuring
   */
  changed_company_id?: string;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * ISO 3166-1 numeric country code
   */
  country?: number;
  /**
   * Date this was initally added to the IGDB database
   */
  created_at?: number;
  /**
   * A free text description of the company
   */
  description?: string;
  developed?: Array<number>;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   */
  logo?: number;
  /**
   * The name of the company
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   */
  parent?: number;
  published?: Array<number>;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  /**
   * The date that the company was founded
   */
  start_date?: number;
  start_date_category?: StartDateCategoryEnum;
  /**
   * The IGDB object unique identifier
   */
  start_date_format?: number;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
  websites?: Array<number>;
}
export namespace CompanyDTO {}
