/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ChangeDateCategoryEnum } from '../enums/descriptor/ChangeDateCategoryEnum';
// May contain unused imports in some cases
// @ts-ignore
import { StartDateCategoryEnum } from '../enums/descriptor/StartDateCategoryEnum';

/**
 * Video game companies, both publishers and developers
 * @export
 * @interface CompanyDTO
 */
export interface CompanyDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CompanyDTO
   */
  id?: number;
  /**
   *
   * @type {ChangeDateCategoryEnum}
   * @memberof CompanyDTO
   */
  change_date_category?: ChangeDateCategoryEnum;
  /**
   * The date when a compnay got a new ID
   * @type {number}
   * @memberof CompanyDTO
   */
  change_date?: number;
  /**
   * The new ID for a company that has gone through a merger or restructuring
   * @type {string}
   * @memberof CompanyDTO
   */
  changed_company_id?: string;
  /**
   * ISO 3166-1 numeric country code
   * @type {number}
   * @memberof CompanyDTO
   */
  country?: number;
  /**
   * Date this was initally added to the IGDB database
   * @type {number}
   * @memberof CompanyDTO
   */
  created_at?: number;
  /**
   * A free text description of the company
   * @type {string}
   * @memberof CompanyDTO
   */
  description?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof CompanyDTO
   */
  developed?: Array<number>;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CompanyDTO
   */
  logo?: number;
  /**
   * The name of the company
   * @type {string}
   * @memberof CompanyDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof CompanyDTO
   */
  parent?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof CompanyDTO
   */
  published?: Array<number>;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof CompanyDTO
   */
  slug?: string;
  /**
   * The date that the company was founded
   * @type {number}
   * @memberof CompanyDTO
   */
  start_date?: number;
  /**
   *
   * @type {StartDateCategoryEnum}
   * @memberof CompanyDTO
   */
  start_date_category?: StartDateCategoryEnum;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof CompanyDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof CompanyDTO
   */
  url?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof CompanyDTO
   */
  websites?: Array<number>;
  /**
   * Hash of the object
   * @type {string}
   * @memberof CompanyDTO
   */
  checksum?: string;
}
