/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * URLs related to the event like Twitter, Facebook, and Youtube
 * @export
 * @interface EventNetworkDTO
 */
export interface EventNetworkDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof EventNetworkDTO
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof EventNetworkDTO
   */
  event?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof EventNetworkDTO
   */
  url?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof EventNetworkDTO
   */
  network_type?: number;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof EventNetworkDTO
   */
  created_at?: number;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof EventNetworkDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof EventNetworkDTO
   */
  checksum?: string;
}
