/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Logo for the event
 */
export interface EventLogo {
  alpha_channel?: boolean;
  animated?: boolean;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The IGDB object unique identifier
   */
  event?: number;
  /**
   * The height of the image in pixels
   */
  height?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The ID of the image used to construct an IGDB image link
   */
  image_id?: string;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
  /**
   * The width of the image in pixels
   */
  width?: number;
}
