/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Gaming events like GamesCom, Tokyo Game Show, PAX, or GSL
 */
export interface Event {
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The description of the event
   */
  description?: string;
  /**
   * End time of the event in UTC
   */
  end_time?: number;
  /**
   * The IGDB object unique identifier
   */
  event_logo?: number;
  event_networks?: Array<number>;
  games?: Array<number>;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * URL to the livestream of the event.
   */
  live_stream_url?: string;
  /**
   * The name of the event
   */
  name?: string;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  /**
   * Start time of the event in UTC
   */
  start_time?: number;
  /**
   * Timezone the event is in.
   */
  time_zone?: string;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  videos?: Array<number>;
}
