/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The external platform the game is on   1: steam   5: gog   10: youtube   11: microsoft   13: apple   14: twitch   15: android   20: amazon_asin   22: amazon_luna   23: amazon_adg   26: epic_game_store   28: oculus   29: utomik   30: itch_io   31: xbox_marketplace   32: kartridge   36: playstation_store_us   37: focus_entertainment   54: xbox_game_pass_ultimate_cloud   55: gamejolt
 */
export type ExternalGameCategoryEnums =
  | 1
  | 5
  | 10
  | 11
  | 13
  | 14
  | 15
  | 20
  | 22
  | 23
  | 26
  | 28
  | 29
  | 30
  | 31
  | 32
  | 36
  | 37
  | 54
  | 55;

export const ExternalGameCategoryEnums = {
  amazon_adg: 23 as ExternalGameCategoryEnums,
  amazon_asin: 20 as ExternalGameCategoryEnums,
  amazon_luna: 22 as ExternalGameCategoryEnums,
  android: 15 as ExternalGameCategoryEnums,
  apple: 13 as ExternalGameCategoryEnums,
  epic_game_store: 26 as ExternalGameCategoryEnums,
  focus_entertainment: 37 as ExternalGameCategoryEnums,
  gamejolt: 55 as ExternalGameCategoryEnums,
  gog: 5 as ExternalGameCategoryEnums,
  itch_io: 30 as ExternalGameCategoryEnums,
  kartridge: 32 as ExternalGameCategoryEnums,
  microsoft: 11 as ExternalGameCategoryEnums,
  oculus: 28 as ExternalGameCategoryEnums,
  playstation_store_us: 36 as ExternalGameCategoryEnums,
  steam: 1 as ExternalGameCategoryEnums,
  twitch: 14 as ExternalGameCategoryEnums,
  utomik: 29 as ExternalGameCategoryEnums,
  xbox_game_pass_ultimate_cloud: 54 as ExternalGameCategoryEnums,
  xbox_marketplace: 31 as ExternalGameCategoryEnums,
  youtube: 10 as ExternalGameCategoryEnums,
};
