/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ExternalGameCategoryEnums } from '../enum/descriptor/ExternalGameCategoryEnums';
// May contain unused imports in some cases
// @ts-ignore
import { ExternalGameMediaEnums } from '../enum/descriptor/ExternalGameMediaEnums';

/**
 * Game IDs on other services
 * @export
 * @interface ExternalGameDTO
 */
export interface ExternalGameDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ExternalGameDTO
   */
  id?: number;
  /**
   *
   * @type {ExternalGameCategoryEnums}
   * @memberof ExternalGameDTO
   */
  category?: ExternalGameCategoryEnums;
  /**
   * The ISO country code of the external game product.
   * @type {Array<number>}
   * @memberof ExternalGameDTO
   */
  countries?: Array<number>;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof ExternalGameDTO
   */
  created_at?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ExternalGameDTO
   */
  game?: number;
  /**
   *
   * @type {ExternalGameMediaEnums}
   * @memberof ExternalGameDTO
   */
  media?: ExternalGameMediaEnums;
  /**
   * The name of the game according to the other service
   * @type {string}
   * @memberof ExternalGameDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ExternalGameDTO
   */
  platform?: number;
  /**
   * The other services ID for this game
   * @type {string}
   * @memberof ExternalGameDTO
   */
  uid?: string;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof ExternalGameDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof ExternalGameDTO
   */
  url?: string;
  /**
   * The year in full (2018)
   * @type {number}
   * @memberof ExternalGameDTO
   */
  year?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof ExternalGameDTO
   */
  checksum?: string;
}
