/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GameVersionIncludedFeatureEnums } from '../enum/descriptor/GameVersionFeatureCategoryEnums';

/**
 * The bool/text value of the feature
 * @export
 * @interface GameVersionFeatureValueDTO
 */
export interface GameVersionFeatureValueDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionFeatureValueDTO
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionFeatureValueDTO
   */
  game?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionFeatureValueDTO
   */
  game_feature?: number;
  /**
   *
   * @type {GameVersionIncludedFeatureEnums}
   * @memberof GameVersionFeatureValueDTO
   */
  included_feature?: GameVersionIncludedFeatureEnums;
  /**
   * The text value of this feature
   * @type {string}
   * @memberof GameVersionFeatureValueDTO
   */
  note?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof GameVersionFeatureValueDTO
   */
  checksum?: string;
}
