/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Game localization for a game
 * @export
 * @interface GameLocalizationDTO
 */
export interface GameLocalizationDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  id?: number;
  /**
   * The localized name
   * @type {string}
   * @memberof GameLocalizationDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  game?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  cover?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  region?: number;
  /**
   *
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof GameLocalizationDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof GameLocalizationDTO
   */
  checksum?: string;
}
