/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameVersionFeatureCategoryEnums } from './gameVersionFeatureCategoryEnums';

/**
 * Features and descriptions of what makes each version/edition different from the main game
 */
export interface GameVersionFeatures {
  category?: GameVersionFeatureCategoryEnums;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * The description of the feature
   */
  description?: string;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * Position of this feature in the list of features
   */
  position?: number;
  /**
   * The title of the version/addition/DLC
   */
  title?: string;
  /**
   * The bool/text value of the feature
   */
  values?: Array<number>;
}
export namespace GameVersionFeatures {}
