/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AgeRatingEnums } from './ageRatingEnums';
import { GameCategoryEnums } from './gameCategoryEnums';
import { GameStatusEnums } from './gameStatusEnums';

/**
 * Video Games!
 */
export interface GameDTO {
  age_ratings?: Array<AgeRatingEnums>;
  /**
   * Rating based on external critic scores
   */
  aggregated_rating?: number;
  /**
   * Number of external critic scores
   */
  aggregated_rating_count?: number;
  alternative_names?: Array<number>;
  artworks?: Array<number>;
  bundles?: Array<number>;
  category?: GameCategoryEnums;
  /**
   * Hash of the object
   */
  checksum?: string;
  collections?: Array<number>;
  /**
   * The IGDB object unique identifier
   */
  cover?: number;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  dlcs?: Array<number>;
  expanded_games?: Array<number>;
  expansions?: Array<number>;
  external_games?: Array<number>;
  /**
   * The first release date for this game
   */
  first_release_date?: number;
  forks?: Array<number>;
  /**
   * The main franchise
   */
  franchise?: string;
  /**
   * Other franchises the game belongs to
   */
  franchises?: Array<number>;
  /**
   * The game engine used in this game
   */
  game_engines?: Array<number>;
  /**
   * Supported game localizations for this game. A region can have at most one game localization for a given game
   */
  game_localizations?: Array<number>;
  /**
   * Modes of gameplay
   */
  game_modes?: Array<number>;
  /**
   * The IGDB object unique identifier
   */
  game_status?: number;
  /**
   * The IGDB object unique identifier
   */
  game_type?: number;
  /**
   * Genres of the game
   */
  genres?: Array<number>;
  /**
   * Number of follows a game gets before release
   */
  hypes?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * Companies who developed this game
   */
  involved_companies?: Array<number>;
  /**
   * Associated keywords
   */
  keywords?: Array<number>;
  /**
   * Supported Languages for this game
   */
  language_supports?: Array<number>;
  /**
   * Multiplayer modes for this game
   */
  multiplayer_modes?: Array<number>;
  /**
   * The name of the Game
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   */
  parent_game?: number;
  /**
   * Platforms this game was released on
   */
  platforms?: Array<number>;
  /**
   * The main perspective of the player
   */
  player_perspectives?: Array<number>;
  /**
   * Ports of this game
   */
  ports?: Array<number>;
  /**
   * Average IGDB user rating
   */
  rating?: number;
  /**
   * Total number of IGDB user ratings
   */
  rating_count?: number;
  /**
   * Release dates of this game
   */
  release_dates?: Array<number>;
  /**
   * Remakes of this game
   */
  remakes?: Array<number>;
  /**
   * Remasters of this game
   */
  remasters?: Array<number>;
  /**
   * Screenshots of this game
   */
  screenshots?: Array<number>;
  /**
   * Similar games
   */
  similar_games?: Array<number>;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  /**
   * Standalone expansions of this game
   */
  standalone_expansions?: Array<number>;
  status?: GameStatusEnums;
  /**
   * A short description of a games story
   */
  storyline?: string;
  /**
   * A description of the game
   */
  summary?: string;
  /**
   * Related entities in the IGDB API
   */
  tags?: Array<number>;
  /**
   * Themes of the game
   */
  themes?: Array<number>;
  /**
   * Average rating based on both IGDB user and external critic scores
   */
  total_rating?: number;
  /**
   * Total number of user and external critic scores
   */
  total_rating_count?: number;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
  /**
   * If a version, this is the main game
   */
  version_parent?: Array<number>;
  /**
   * Title of this version (i.e Gold edition)
   */
  version_title?: string;
  /**
   * Videos of this game
   */
  videos?: Array<number>;
  /**
   * Websites associated with this game
   */
  websites?: Array<number>;
}
export namespace GameDTO {}
