/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Average time to beat times for a game.
 */
export interface GameTimeToBeat {
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Average time (in seconds) to finish the game to 100% completion.
   */
  completely?: number;
  /**
   * Total number of time to beat submissions for this game
   */
  count?: number;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The IGDB object unique identifier
   */
  game_id?: number;
  /**
   * Average time (in seconds) to finish the game to its credits without spending notable time on extras such as side quests.
   */
  hastily?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * Average time (in seconds) to finish the game while mixing in some extras such as side quests without being overly thorough.
   */
  normally?: number;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
}
