/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A game\'s category/catagories   0: main_game   1: dlc_addon   2: expansion   3: bundle   4: standalone_expansion   5: mod   6: episode   7: season   8: remake   9: remaster   10: expanded_game   11: port   12: fork   13: pack   14: update
 */
export type GameCategoryEnums =
  | 0
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 7
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14;

export const GameCategoryEnums = {
  bundle: 3 as GameCategoryEnums,
  dlc_addon: 1 as GameCategoryEnums,
  episode: 6 as GameCategoryEnums,
  expanded_game: 10 as GameCategoryEnums,
  expansion: 2 as GameCategoryEnums,
  fork: 12 as GameCategoryEnums,
  main_game: 0 as GameCategoryEnums,
  mod: 5 as GameCategoryEnums,
  pack: 13 as GameCategoryEnums,
  port: 11 as GameCategoryEnums,
  remake: 8 as GameCategoryEnums,
  remaster: 9 as GameCategoryEnums,
  season: 7 as GameCategoryEnums,
  standalone_expansion: 4 as GameCategoryEnums,
  update: 14 as GameCategoryEnums,
};
