/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { AgeRatingEnum } from '../enums/descriptor/AgeRatingEnum';
// May contain unused imports in some cases
// @ts-ignore
import { GameCategoryEnums } from './game-category-enums';
// May contain unused imports in some cases
// @ts-ignore
import { GameStatusEnums } from './game-status-enums';

/**
 * Video games!
 * @export
 * @interface GameDTO
 */
export interface GameDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameDTO
   */
  id?: number;
  /**
   *
   * @type {Array<AgeRatingEnums>}
   * @memberof GameDTO
   */
  age_ratings?: Array<AgeRatingEnum>;
  /**
   * Rating based on external critic scores
   * @type {number}
   * @memberof GameDTO
   */
  aggregated_rating?: number;
  /**
   * Number of external critic scores
   * @type {number}
   * @memberof GameDTO
   */
  aggregated_rating_count?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  alternative_names?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  artworks?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  bundles?: Array<number>;
  /**
   *
   * @type {GameCategoryEnums}
   * @memberof GameDTO
   */
  category?: GameCategoryEnums;
  /**
   * DEPRRICATED - Use collections field. Reference ID for collection
   * @type {number}
   * @memberof GameDTO
   * @deprecated
   */
  collection?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  collections?: Array<number>;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameDTO
   */
  cover?: number;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof GameDTO
   */
  created_at?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  dlcs?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  expanded_games?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  expansions?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  external_games?: Array<number>;
  /**
   * DEPRECATED- TO BE REMOVED. The number of people following a game
   * @type {number}
   * @memberof GameDTO
   * @deprecated
   */
  follows?: number;
  /**
   * The first release date for this game
   * @type {number}
   * @memberof GameDTO
   */
  first_release_date?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof GameDTO
   */
  forks?: Array<number>;
  /**
   * The main franchise
   * @type {string}
   * @memberof GameDTO
   */
  franchise?: string;
  /**
   * Other franchises the game belongs to
   * @type {Array<number>}
   * @memberof GameDTO
   */
  franchises?: Array<number>;
  /**
   * The game engine used in this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  game_engines?: Array<number>;
  /**
   * Supported game localizations for this game. A region can have at most one game localization for a given game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  game_localizations?: Array<number>;
  /**
   * Modes of gameplay
   * @type {Array<number>}
   * @memberof GameDTO
   */
  game_modes?: Array<number>;
  /**
   * Genres of the game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  genres?: Array<number>;
  /**
   * Number of follows a game gets before release
   * @type {number}
   * @memberof GameDTO
   */
  hypes?: number;
  /**
   * Companies who developed this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  involved_companies?: Array<number>;
  /**
   * Associated keywords
   * @type {Array<number>}
   * @memberof GameDTO
   */
  keywords?: Array<number>;
  /**
   * Supported Languages for this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  language_supports?: Array<number>;
  /**
   * Multiplayer modes for this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  multiplayer_modes?: Array<number>;
  /**
   * The name of the game
   * @type {string}
   * @memberof GameDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameDTO
   */
  parent_game?: number;
  /**
   * Platforms this game was released on
   * @type {Array<number>}
   * @memberof GameDTO
   */
  platforms?: Array<number>;
  /**
   * The main perspective of the player
   * @type {Array<number>}
   * @memberof GameDTO
   */
  player_perspectives?: Array<number>;
  /**
   * Ports of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  ports?: Array<number>;
  /**
   * Average IGDB user rating
   * @type {number}
   * @memberof GameDTO
   */
  rating?: number;
  /**
   * Total number of IGDB user ratings
   * @type {number}
   * @memberof GameDTO
   */
  rating_count?: number;
  /**
   * Release dates of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  release_dates?: Array<number>;
  /**
   * Remakes of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  remakes?: Array<number>;
  /**
   * Remasters of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  remasters?: Array<number>;
  /**
   * Screenshots of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  screenshots?: Array<number>;
  /**
   * Similar GameDTO
   * @type {Array<number>}
   * @memberof GameDTO
   */
  similar_games?: Array<number>;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof GameDTO
   */
  slug?: string;
  /**
   * Standalone expansions of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  standalone_expansions?: Array<number>;
  /**
   *
   * @type {GameStatusEnums}
   * @memberof GameDTO
   */
  status?: GameStatusEnums;
  /**
   * A short description of a GameDTO story
   * @type {string}
   * @memberof GameDTO
   */
  storyline?: string;
  /**
   * A description of the game
   * @type {string}
   * @memberof GameDTO
   */
  summary?: string;
  /**
   * Related entities in the IGDB API
   * @type {Array<number>}
   * @memberof GameDTO
   */
  tags?: Array<number>;
  /**
   * Themes of the game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  themes?: Array<number>;
  /**
   * Average rating based on both IGDB user and external critic scores
   * @type {number}
   * @memberof GameDTO
   */
  total_rating?: number;
  /**
   * Total number of user and external critic scores
   * @type {number}
   * @memberof GameDTO
   */
  total_rating_count?: number;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof GameDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof GameDTO
   */
  url?: string;
  /**
   * If a version, this is the main game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  version_parent?: Array<number>;
  /**
   * Title of this version (i.e Gold edition)
   * @type {string}
   * @memberof GameDTO
   */
  version_title?: string;
  /**
   * Videos of this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  videos?: Array<number>;
  /**
   * Websites associated with this game
   * @type {Array<number>}
   * @memberof GameDTO
   */
  websites?: Array<number>;
  /**
   * Hash of the object
   * @type {string}
   * @memberof GameDTO
   */
  checksum?: string;
}
