/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { GameVersionFeatureCategoryEnums } from '../enum/descriptor/GameVersionFeatureCategoryEnums';

/**
 * Features and descriptions of what makes each version/edition different from the main game
 * @export
 * @interface GameVersionFeaturesDTO
 */
export interface GameVersionFeaturesDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionFeaturesDTO
   */
  id?: number;
  /**
   *
   * @type {GameVersionFeatureCategoryEnums}
   * @memberof GameVersionFeaturesDTO
   */
  category?: GameVersionFeatureCategoryEnums;
  /**
   * The description of the feature
   * @type {string}
   * @memberof GameVersionFeaturesDTO
   */
  description?: string;
  /**
   * Position of this feature in the list of features
   * @type {number}
   * @memberof GameVersionFeaturesDTO
   */
  position?: number;
  /**
   * The title of the version/addition/DLC
   * @type {string}
   * @memberof GameVersionFeaturesDTO
   */
  title?: string;
  /**
   * The bool/text value of the feature
   * @type {Array<number>}
   * @memberof GameVersionFeaturesDTO
   */
  values?: Array<number>;
  /**
   * Hash of the object
   * @type {string}
   * @memberof GameVersionFeaturesDTO
   */
  checksum?: string;
}
