/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A game\'s operational status   0: released   2: alpha   3: beta   4: early_access   5: offline   6: cancelled   7: rumored   8: delisted
 */
export type GameStatusEnums = 0 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

export const GameStatusEnums = {
  alpha: 2 as GameStatusEnums,
  beta: 3 as GameStatusEnums,
  cancelled: 6 as GameStatusEnums,
  delisted: 8 as GameStatusEnums,
  early_access: 4 as GameStatusEnums,
  offline: 5 as GameStatusEnums,
  released: 0 as GameStatusEnums,
  rumored: 7 as GameStatusEnums,
};
