/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Video game engines such as unreal engine
 */
export interface GameEngine {
  /**
   * Hash of the object
   */
  checksum?: string;
  companies?: Array<number>;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * Description of the game engine
   */
  description?: string;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   */
  logo?: number;
  /**
   * Name of the game engine
   */
  name?: string;
  /**
   * Platforms this game engine was deployed on
   */
  platforms?: Array<number>;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  /**
   * The last date this entry was updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
}
