/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Details about game editions and versions. (DLC and more)
 * @export
 * @interface GameVersionDTO
 */
export interface GameVersionDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionDTO
   */
  id?: number;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof GameVersionDTO
   */
  created_at?: number;
  /**
   * Features and descriptions of what makes each version/edition different from the main game
   * @type {Array<number>}
   * @memberof GameVersionDTO
   */
  features?: Array<number>;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof GameVersionDTO
   */
  game?: number;
  /**
   * Game Versions and Editions
   * @type {Array<number>}
   * @memberof GameVersionDTO
   */
  games?: Array<number>;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof GameVersionDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof GameVersionDTO
   */
  url?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof GameVersionDTO
   */
  checksum?: string;
}
