/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Involved companies
 * @export
 * @interface InvolvedCompanyDTO
 */
export interface InvolvedCompanyDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof InvolvedCompanyDTO
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof InvolvedCompanyDTO
   */
  company?: number;
  /**
   * Date this was initally added to the IGDB database
   * @type {number}
   * @memberof InvolvedCompanyDTO
   */
  created_at?: number;
  /**
   * Is the company a/the developer?
   * @type {boolean}
   * @memberof InvolvedCompanyDTO
   */
  developer?: boolean;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof InvolvedCompanyDTO
   */
  game?: number;
  /**
   * Did the company port the game?
   * @type {boolean}
   * @memberof InvolvedCompanyDTO
   */
  porting?: boolean;
  /**
   * Did the company publish the game?
   * @type {boolean}
   * @memberof InvolvedCompanyDTO
   */
  publisher?: boolean;
  /**
   * Did the company suppport the game?
   * @type {boolean}
   * @memberof InvolvedCompanyDTO
   */
  supporting?: boolean;
  /**
   * The last date this entry was updated in the IGDB database
   * @type {number}
   * @memberof InvolvedCompanyDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof InvolvedCompanyDTO
   */
  checksum?: string;
}
