/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Games can be played with different languages for voice acting, subtitles, or the interface language.
 * @export
 * @interface LanguageSupportDTO
 */
export interface LanguageSupportDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  id?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  game?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  language?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  language_support_type?: number;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof LanguageSupportDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof LanguageSupportDTO
   */
  checksum?: string;
}
