/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Language Support Types contains the identifiers for the support types that Language Support uses.
 * @export
 * @interface LanguageSupportTypeDTO
 */
export interface LanguageSupportTypeDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageSupportTypeDTO
   */
  id?: number;
  /**
   * The name of the method of support. (Audio, Subtitles, etc)
   * @type {string}
   * @memberof LanguageSupportTypeDTO
   */
  name?: string;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof LanguageSupportTypeDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof LanguageSupportTypeDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof LanguageSupportTypeDTO
   */
  checksum?: string;
}
