/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Languages that are used in the LanguageDTO Support endpoint.
 * @export
 * @interface LanguageDTO
 */
export interface LanguageDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof LanguageDTO
   */
  id?: number;
  /**
   * The name of the localization
   * @type {string}
   * @memberof LanguageDTO
   */
  name?: string;
  /**
   * The native name of the language
   * @type {string}
   * @memberof LanguageDTO
   */
  native_name?: string;
  /**
   * The combination of language code and Country code (en-US)
   * @type {string}
   * @memberof LanguageDTO
   */
  locale?: string;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof LanguageDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof LanguageDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof LanguageDTO
   */
  checksum?: string;
}
