/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Data about the supported multiplayer types
 */
export interface MultiplayerModeDTO {
  /**
   * True if the game supports campaign coop
   */
  camapigncoop?: boolean;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * True if the game supports drop in/out multiplayer
   */
  dropin?: boolean;
  /**
   * The IGDB object unique identifier
   */
  game?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * True if the game supports LAN coop
   */
  lancoop?: boolean;
  /**
   * Maximum number of offline players in offline coop
   */
  offliencoopmax?: number;
  /**
   * True if the game supports offline coop
   */
  offlinecoop?: number;
  /**
   * Maximum number of players in offline multiplayer
   */
  offlinemax?: number;
  /**
   * True if the game supports online coop
   */
  onlinecoop?: boolean;
  /**
   * Maximum number of online players in online coop
   */
  onlinecoopmax?: number;
  /**
   * Maximum number of online players in online coop
   */
  onlinemax?: number;
  /**
   * The IGDB object unique identifier
   */
  platform?: number;
  /**
   * True if the game supports, split screen, offline multiplayer
   */
  splitscreen?: boolean;
  /**
   * True if the game supports split screen, online multiplayer
   */
  splitscreenonline?: boolean;
}
