/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatformCategoryEnums } from './platformCategoryEnums';

/**
 * The hardware used to run the game or game delivery network
 */
export interface PlatformDTO {
  /**
   * An abbreviation of the platform name
   */
  abbreviation?: string;
  /**
   * An alternative name for the platform
   */
  alternative_name?: string;
  category?: PlatformCategoryEnums;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The generation of the platform
   */
  generation?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The name of the platform
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   */
  platform_family?: number;
  /**
   * The IGDB object unique identifier
   */
  platform_logo?: number;
  /**
   * The IGDB object unique identifier
   */
  platform_type?: number;
  /**
   * A url-safe, unique, lower-case version of the name
   */
  slug?: string;
  /**
   * The summary of the first Version of this platform
   */
  summary?: string;
  /**
   * Date this was last updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   */
  url?: string;
  versions?: Array<number>;
  websites?: Array<number>;
}
export namespace PlatformDTO {}
