/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The platform website   1: official   2: wikia   3: wikipedia   4: facebook   5: twitter   6: twitch   8: instagram   9: youtube   10: iphone   11: ipad   12: android   13: steam   14: reddit   15: discord   16: google_plus   17: tumblr   18: linkedin   19: pinterest   20: soundcloud
 */
export type PlatformWebsiteCategoryEnums =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18
  | 19
  | 20;

export const PlatformWebsiteCategoryEnums = {
  android: 12 as PlatformWebsiteCategoryEnums,
  discord: 15 as PlatformWebsiteCategoryEnums,
  facebook: 4 as PlatformWebsiteCategoryEnums,
  google_plus: 16 as PlatformWebsiteCategoryEnums,
  instagram: 8 as PlatformWebsiteCategoryEnums,
  ipad: 11 as PlatformWebsiteCategoryEnums,
  iphone: 10 as PlatformWebsiteCategoryEnums,
  linkedin: 18 as PlatformWebsiteCategoryEnums,
  official: 1 as PlatformWebsiteCategoryEnums,
  pinterest: 19 as PlatformWebsiteCategoryEnums,
  reddit: 14 as PlatformWebsiteCategoryEnums,
  soundcloud: 20 as PlatformWebsiteCategoryEnums,
  steam: 13 as PlatformWebsiteCategoryEnums,
  tumblr: 17 as PlatformWebsiteCategoryEnums,
  twitch: 6 as PlatformWebsiteCategoryEnums,
  twitter: 5 as PlatformWebsiteCategoryEnums,
  wikia: 2 as PlatformWebsiteCategoryEnums,
  wikipedia: 3 as PlatformWebsiteCategoryEnums,
  youtube: 9 as PlatformWebsiteCategoryEnums,
};
