/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { PlatformCategoryEnums } from '../enums/descriptor/PlatformCategoryEnums';

/**
 * The hardware used to run the game or game delivery network
 * @export
 * @interface PlatformDTO
 */
export interface PlatformDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformDTO
   */
  id?: number;
  /**
   * An abbreviation of the platform name
   * @type {string}
   * @memberof PlatformDTO
   */
  abbreviation?: string;
  /**
   * An alternative name for the platform
   * @type {string}
   * @memberof PlatformDTO
   */
  alternative_name?: string;
  /**
   *
   * @type {PlatformCategoryEnums}
   * @memberof PlatformDTO
   */
  category?: PlatformCategoryEnums;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof PlatformDTO
   */
  created_at?: number;
  /**
   * The generation of the platform
   * @type {number}
   * @memberof PlatformDTO
   */
  generation?: number;
  /**
   * The name of the platform
   * @type {string}
   * @memberof PlatformDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformDTO
   */
  platform_family?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformDTO
   */
  platform_logo?: number;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof PlatformDTO
   */
  slug?: string;
  /**
   * The summary of the first Version of this platform
   * @type {string}
   * @memberof PlatformDTO
   */
  summary?: string;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof PlatformDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof PlatformDTO
   */
  url?: string;
  /**
   *
   * @type {Array<number>}
   * @memberof PlatformDTO
   */
  versions?: Array<number>;
  /**
   *
   * @type {Array<number>}
   * @memberof PlatformDTO
   */
  websites?: Array<number>;
  /**
   * Hash of the object
   * @type {string}
   * @memberof PlatformDTO
   */
  checksum?: string;
}
