/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The category of the platform   1: console   2: arcade   3: platform   4: operating_system   5: portable_console   6: computer
 */
export type PlatformCategoryEnums = 1 | 2 | 3 | 4 | 5 | 6;

export const PlatformCategoryEnums = {
  arcade: 2 as PlatformCategoryEnums,
  computer: 6 as PlatformCategoryEnums,
  console: 1 as PlatformCategoryEnums,
  operating_system: 4 as PlatformCategoryEnums,
  platform: 3 as PlatformCategoryEnums,
  portable_console: 5 as PlatformCategoryEnums,
};
