/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The specific platform and the specifications (Xbox Series X, Playstation 5)
 * @export
 * @interface PlatformVersionDTO
 */
export interface PlatformVersionDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformVersionDTO
   */
  id?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof PlatformVersionDTO
   */
  companies?: Array<number>;
  /**
   * The network capabilities
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  connectivity?: string;
  /**
   * The integrated central processing unit
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  cpu?: string;
  /**
   * The graphics chipset
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  graphics?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformVersionDTO
   */
  main_manufacturer?: number;
  /**
   * The type of media this version accepts
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  media?: string;
  /**
   * How much memory there is
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  memory?: string;
  /**
   * The name of the platform version
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  name?: string;
  /**
   * The online service, like Xbox Live
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  online?: string;
  /**
   * The operating system installed on the platform version
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  os?: string;
  /**
   * The output video rate
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  output?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformVersionDTO
   */
  platform_logo?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof PlatformVersionDTO
   */
  platform_version_release_dates?: Array<number>;
  /**
   * The maximum resolution
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  resolutions?: string;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  slug?: string;
  /**
   * The sound chipset
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  sound?: string;
  /**
   * How much storage there is
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  storage?: string;
  /**
   * A short summary
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  summary?: string;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  url?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof PlatformVersionDTO
   */
  checksum?: string;
}
