/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A platform developer
 * @export
 * @interface PlatformVersionCompanyDTO
 */
export interface PlatformVersionCompanyDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformVersionCompanyDTO
   */
  id?: number;
  /**
   * Any notable comments about the developer
   * @type {string}
   * @memberof PlatformVersionCompanyDTO
   */
  comment?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof PlatformVersionCompanyDTO
   */
  company?: number;
  /**
   * If the company is the developer
   * @type {boolean}
   * @memberof PlatformVersionCompanyDTO
   */
  developer?: boolean;
  /**
   * If the company is the manufactuer
   * @type {boolean}
   * @memberof PlatformVersionCompanyDTO
   */
  manufacturer?: boolean;
  /**
   * Hash of the object
   * @type {string}
   * @memberof PlatformVersionCompanyDTO
   */
  checksum?: string;
}
