/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlatformWebsiteCategoryEnums } from './platformWebsiteCategoryEnums';

/**
 * The main website for the platform
 */
export interface PlatformWebsiteDTO {
  category?: PlatformWebsiteCategoryEnums;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  trusted?: boolean;
  /**
   * The main platform address (URL) of the platform
   */
  url?: string;
}
export namespace PlatformWebsiteDTO {}
