/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RegionDTO for game localization
 * @export
 * @interface RegionDTO
 */
export interface RegionDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof RegionDTO
   */
  id?: number;
  /**
   * The name of the region
   * @type {string}
   * @memberof RegionDTO
   */
  name?: string;
  /**
   * Whether the region is a local or continent
   * @type {string}
   * @memberof RegionDTO
   */
  category?: RegionCategoryEnum;
  /**
   * This is the identifier of each region
   * @type {any}
   * @memberof RegionDTO
   */
  identifier?: any;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof RegionDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof RegionDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof RegionDTO
   */
  checksum?: string;
}

export const RegionCategoryEnum = {
  Locale: "locale",
  Continent: "continent",
} as const;

export type RegionCategoryEnum =
  (typeof RegionCategoryEnum)[keyof typeof RegionCategoryEnum];
