/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Region for game localization
 */
export interface Region {
  /**
   * Whether the region is a local or continent
   */
  category?: Region.CategoryEnum;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * This is the identifier of each region
   */
  identifier?: any | null;
  /**
   * The name of the region
   */
  name?: string;
  /**
   * Date this was last updated in the IGDB database
   */
  updated_at?: number;
}
export namespace Region {
  export type CategoryEnum = 'continent' | 'locale';
  export const CategoryEnum = {
    Continent: 'continent' as CategoryEnum,
    Locale: 'locale' as CategoryEnum,
  };
}
