/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { ReleaseDateCategoryEnums } from '../enum/descriptor/ReleaseDateCategoryEnums';
// May contain unused imports in some cases
// @ts-ignore
import { ReleaseDateRegionEnum } from '../enum/descriptor/ReleaseDateRegionEnum';

/**
 * A handy endpoint that extends platform release dates. Used to dig deeper into release dates, platforms and versions.
 * @export
 * @interface ReleaseDateDTO
 */
export interface ReleaseDateDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  id?: number;
  /**
   *
   * @type {ReleaseDateCategoryEnums}
   * @memberof ReleaseDateDTO
   */
  category?: ReleaseDateCategoryEnums;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  created_at?: number;
  /**
   * The release date
   * @type {string}
   * @memberof ReleaseDateDTO
   */
  date?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  game?: number;
  /**
   * A human readable version of the release date
   * @type {string}
   * @memberof ReleaseDateDTO
   */
  human?: string;
  /**
   * The month as an integer starting at 1 (January)
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  m?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  platform?: number;
  /**
   *
   * @type {ReleaseDateRegionEnum}
   * @memberof ReleaseDateDTO
   */
  region?: ReleaseDateRegionEnum;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  updated_at?: number;
  /**
   * The year in full (2018)
   * @type {number}
   * @memberof ReleaseDateDTO
   */
  y?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof ReleaseDateDTO
   */
  checksum?: string;
}
