/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An endpoint to provide definition of all of the current release date statuses.
 */
export interface ReleaseDateRegionDTO {
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * Regions for release dates
   */
  region?: string;
  /**
   * Date this was last updated in the IGDB database
   */
  updated_at?: number;
}
