/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReleaseDateCategoryEnums } from './releaseDateCategoryEnums';
import { ReleaseDateRegionEnum } from './releaseDateRegionEnum';

/**
 * A handy endpoint that extends platform release dates. Used to dig deeper into release dates, platforms and versions.
 */
export interface ReleaseDate {
  category?: ReleaseDateCategoryEnums;
  /**
   * Hash of the object
   */
  checksum?: string;
  /**
   * Date this was initially added to the IGDB database
   */
  created_at?: number;
  /**
   * The release date
   */
  date?: string;
  /**
   * The IGDB object unique identifier
   */
  date_format?: number;
  /**
   * The IGDB object unique identifier
   */
  game?: number;
  /**
   * A human readable version of the release date
   */
  human?: string;
  /**
   * The IGDB object unique identifier
   */
  id?: number;
  /**
   * The month as an integer starting at 1 (January)
   */
  m?: number;
  /**
   * The IGDB object unique identifier
   */
  platform?: number;
  region?: ReleaseDateRegionEnum;
  /**
   * The IGDB object unique identifier
   */
  release_region?: number;
  /**
   * Date this was last updated in the IGDB database
   */
  updated_at?: number;
  /**
   * The year in full (2018)
   */
  y?: number;
}
export namespace ReleaseDate {}
