/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An endpoint to provide definition of all of the current release date statuses.
 * @export
 * @interface ReleaseDateStatusDTO
 */
export interface ReleaseDateStatusDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ReleaseDateStatusDTO
   */
  id?: number;
  /**
   * The name of the release date status
   * @type {string}
   * @memberof ReleaseDateStatusDTO
   */
  name?: string;
  /**
   * The description of the release date status.
   * @type {string}
   * @memberof ReleaseDateStatusDTO
   */
  description?: string;
  /**
   * Date this was initially added to the IGDB database
   * @type {number}
   * @memberof ReleaseDateStatusDTO
   */
  created_at?: number;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof ReleaseDateStatusDTO
   */
  updated_at?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof ReleaseDateStatusDTO
   */
  checksum?: string;
}
