/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * An enum of the region for the release date   1: europe   2: north_america   3: australia   4: new_zealand   5: japan   6: china   7: asia   8: worldwide   9: korea   10: brazil
 */
export type ReleaseDateRegionEnum = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

export const ReleaseDateRegionEnum = {
  asia: 7 as ReleaseDateRegionEnum,
  australia: 3 as ReleaseDateRegionEnum,
  brazil: 10 as ReleaseDateRegionEnum,
  china: 6 as ReleaseDateRegionEnum,
  europe: 1 as ReleaseDateRegionEnum,
  japan: 5 as ReleaseDateRegionEnum,
  korea: 9 as ReleaseDateRegionEnum,
  new_zealand: 4 as ReleaseDateRegionEnum,
  north_america: 2 as ReleaseDateRegionEnum,
  worldwide: 8 as ReleaseDateRegionEnum,
};
