/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Search IGDB and get the IDs of items matching your search
 * @export
 * @interface SearchDTO
 */
export interface SearchDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof SearchDTO
   */
  alternative_name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  character?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  collection?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  company?: number;
  /**
   *
   * @type {string}
   * @memberof SearchDTO
   */
  description?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  game?: number;
  /**
   *
   * @type {string}
   * @memberof SearchDTO
   */
  name?: string;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  platform?: number;
  /**
   * The date this item was initally published by the third party
   * @type {number}
   * @memberof SearchDTO
   */
  published_at?: number;
  /**
   * Reference ID for Test Dummy
   * @type {number}
   * @memberof SearchDTO
   */
  test_dummy?: number;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof SearchDTO
   */
  theme?: number;
  /**
   * Hash of the object
   * @type {string}
   * @memberof SearchDTO
   */
  checksum?: string;
}
