/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Video game themes
 * @export
 * @interface ThemeDTO
 */
export interface ThemeDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof ThemeDTO
   */
  id?: number;
  /**
   * The name of the theme
   * @type {string}
   * @memberof ThemeDTO
   */
  name?: string;
  /**
   * A url-safe, unique, lower-case version of the name
   * @type {string}
   * @memberof ThemeDTO
   */
  slug?: string;
  /**
   * Date this was last updated in the IGDB database
   * @type {number}
   * @memberof ThemeDTO
   */
  updated_at?: number;
  /**
   * The website address (URL) of the item
   * @type {string}
   * @memberof ThemeDTO
   */
  url?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof ThemeDTO
   */
  checksum?: string;
}
