/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { WebsiteCategoryEnums } from '../enum/descriptor/WebsiteCategoryEnums';

/**
 * A website URL, usually associated with a game
 * @export
 * @interface WebsiteDTO
 */
export interface WebsiteDTO {
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof WebsiteDTO
   */
  id?: number;
  /**
   *
   * @type {WebsiteCategoryEnums}
   * @memberof WebsiteDTO
   */
  category?: WebsiteCategoryEnums;
  /**
   * The IGDB object unique identifier
   * @type {number}
   * @memberof WebsiteDTO
   */
  game?: number;
  /**
   *
   * @type {boolean}
   * @memberof WebsiteDTO
   */
  trusted?: boolean;
  /**
   * The main platform address (URL) of the platform
   * @type {string}
   * @memberof WebsiteDTO
   */
  url?: string;
  /**
   * Hash of the object
   * @type {string}
   * @memberof WebsiteDTO
   */
  checksum?: string;
}
