/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across!
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The platform website   1: official   2: wikia   3: wikipedia   4: facebook   5: twitter   6: twitch   8: instagram   9: youtube   10: iphone   11: ipad   12: android   13: steam   14: reddit   15: itch   16: epicgames   17: gog   18: discord
 */
export type WebsiteCategoryEnums =
  | 1
  | 2
  | 3
  | 4
  | 5
  | 6
  | 8
  | 9
  | 10
  | 11
  | 12
  | 13
  | 14
  | 15
  | 16
  | 17
  | 18;

export const WebsiteCategoryEnums = {
  android: 12 as WebsiteCategoryEnums,
  discord: 18 as WebsiteCategoryEnums,
  epicgames: 16 as WebsiteCategoryEnums,
  facebook: 4 as WebsiteCategoryEnums,
  gog: 17 as WebsiteCategoryEnums,
  instagram: 8 as WebsiteCategoryEnums,
  ipad: 11 as WebsiteCategoryEnums,
  iphone: 10 as WebsiteCategoryEnums,
  itch: 15 as WebsiteCategoryEnums,
  official: 1 as WebsiteCategoryEnums,
  reddit: 14 as WebsiteCategoryEnums,
  steam: 13 as WebsiteCategoryEnums,
  twitch: 6 as WebsiteCategoryEnums,
  twitter: 5 as WebsiteCategoryEnums,
  wikia: 2 as WebsiteCategoryEnums,
  wikipedia: 3 as WebsiteCategoryEnums,
  youtube: 9 as WebsiteCategoryEnums,
};
