export enum ExternalGameCategory {
  AmazonADG = 23,
  AmazonASIN = 20,
  AmazonLuna = 22,
  Android = 15,
  Apple = 13,
  EpicGameStore = 26,
  FocusEntertainment = 37,
  GameJolt = 55,
  GOG = 5,
  ItchIO = 30,
  Kartridge = 32,
  Microsoft = 11,
  Oculus = 28,
  PlayStationStoreUS = 36,
  Steam = 1,
  Twitch = 14,
  Utomik = 29,
  XboxGamePassUltimateCloud = 54,
  XboxMarketplace = 31,
  YouTube = 10,
}
