/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * An enum of the date format   0: YYYYMMMMDD   1: YYYYMMMM   2: YYYY   3: YYYYQ1   4: YYYYQ2   5: YYYYQ3   6: YYYYQ4   7: TBD   
 * @export
 * @enum {string}
 */

export const PlatformVersionReleaseDateEnums = {
    /**
    * YYYYMMMMDD
    */
    YYYYMMMMDD: 0,
    /**
    * YYYYMMMM
    */
    YYYYMMMM: 1,
    /**
    * YYYY
    */
    YYYY: 2,
    /**
    * YYYYQ1
    */
    YYYYQ1: 3,
    /**
    * YYYYQ2
    */
    YYYYQ2: 4,
    /**
    * YYYYQ3
    */
    YYYYQ3: 5,
    /**
    * YYYYQ4
    */
    YYYYQ4: 6,
    /**
    * TBD
    */
    TBD: 7
} as const;

export type PlatformVersionReleaseDateEnums = typeof PlatformVersionReleaseDateEnums[keyof typeof PlatformVersionReleaseDateEnums];



