export enum EventField {
  checksum = 'checksum',
  created_at = 'created_at',
  description = 'description',
  end_time = 'end_time',
  event_logo = 'event_logo',
  event_networks = 'event_networks',
  games = 'games',
  live_stream_url = 'live_stream_url',
  name = 'name',
  slug = 'slug',
  start_time = 'start_time',
  time_zone = 'time_zone',
  updated_at = 'updated_at',
  videos = 'videos',
}
export enum ExpandedEventField {
  checksum = 'checksum',
  created_at = 'created_at',
  description = 'description',
  end_time = 'end_time',
  event_logo = 'event_logo.*',
  event_networks = 'event_networks.*',
  games = 'games.*',
  live_stream_url = 'live_stream_url',
  name = 'name',
  slug = 'slug',
  start_time = 'start_time',
  time_zone = 'time_zone',
  updated_at = 'updated_at',
  videos = 'videos.*',
}
