export enum ExternalGameField {
  checksum = 'checksum',
  createdAt = 'createdAt',
  id = 'id',
  updatedAt = 'updatedAt',
  igdbId = 'igdbId',
  category = 'category',
  countries = 'countries',
  igdbCreatedAt = 'igdbCreatedAt',
  game = 'game',
  media = 'media',
  name = 'name',
  platform = 'platform',
  uid = 'uid',
  igdbUpdatedAt = 'igdbUpdatedAt',
  url = 'url',
  year = 'year',
}
export enum ExpandedExternalGameField {
  checksum = 'checksum',
  createdAt = 'createdAt',
  id = 'id',
  updatedAt = 'updatedAt',
  igdbId = 'igdbId',
  category = 'category',
  countries = 'countries',
  igdbCreatedAt = 'igdbCreatedAt',
  game = 'game.*',
  media = 'media',
  name = 'name',
  platform = 'platform.*',
  uid = 'uid',
  igdbUpdatedAt = 'igdbUpdatedAt',
  url = 'url',
  year = 'year',
}
