export enum CompanyField {
  change_date = 'change_date',
  change_date_category = 'change_date_category',
  change_date_format = 'change_date_format',
  changed_company_id = 'changed_company_id',
  checksum = 'checksum',
  country = 'country',
  created_at = 'created_at',
  description = 'description',
  developed = 'developed',
  id = 'id',
  logo = 'logo',
  name = 'name',
  parent = 'parent',
  published = 'published',
  slug = 'slug',
  start_date = 'start_date',
  start_date_category = 'start_date_category',
  start_date_format = 'start_date_format',
  updated_at = 'updated_at',
  url = 'url',
  websites = 'websites',
}

export enum ExpandedCompanyField {
  change_date = 'change_date',
  change_date_category = 'change_date_category',
  changed_company_id = 'changed_company_id.*',
  checksum = 'checksum',
  country = 'country',
  created_at = 'created_at',
  description = 'description',
  developed = 'developed.*',
  id = 'id',
  logo = 'logo.*',
  name = 'name',
  parent = 'parent.*',
  published = 'published.*',
  slug = 'slug',
  start_date = 'start_date',
  start_date_category = 'start_date_category',
  updated_at = 'updated_at',
  url = 'url',
  websites = 'websites.*',
}
