export enum PlatformField {
  abbreviation = 'abbreviation',
  alternative_name = 'alternative_name',
  category = 'category',
  checksum = 'checksum',
  created_at = 'created_at',
  generation = 'generation',
  id = 'id',
  name = 'name',
  platform_family = 'platform_family',
  platform_logo = 'platform_logo',
  slug = 'slug',
  summary = 'summary',
  updated_at = 'updated_at',
  url = 'url',
  versions = 'versions',
  websites = 'websites',
}
export enum ExpandedPlatformField {
  abbreviation = 'abbreviation',
  alternative_name = 'alternative_name',
  category = 'category',
  checksum = 'checksum',
  created_at = 'created_at',
  generation = 'generation',
  id = 'id',
  name = 'name',
  platform_family = 'platform_family.*',
  platform_logo = 'platform_logo.*',
  slug = 'slug',
  summary = 'summary',
  updated_at = 'updated_at',
  url = 'url',
  versions = 'versions.*',
  websites = 'websites.*',
}
