export enum PlatformFields {
  checksum = 'checksum',
  companies = 'companies',
  connectivity = 'connectivity',
  cpu = 'cpu',
  graphics = 'graphics',
  id = 'id',
  main_manufacturer = 'main_manufacturer',
  media = 'media',
  memory = 'memory',
  name = 'name',
  os = 'os',
  output = 'output',
  platform_logo = 'platform_logo',
  platform_version_release_dates = 'platform_version_release_dates',
  resolutions = 'resolutions',
  slug = 'slug',
  sound = 'sound',
  storage = 'storage',
  summary = 'summary',
  url = 'url',
}
export enum ExpandedPlatformFields {
  checksum = 'checksum',
  companies = 'companies.*',
  connectivity = 'connectivity',
  cpu = 'cpu',
  graphics = 'graphics',
  id = 'id',
  main_manufacturer = 'main_manufacturer.*',
  media = 'media',
  memory = 'memory',
  name = 'name',
  os = 'os',
  output = 'output',
  platform_logo = 'platform_logo.*',
  platform_version_release_dates = 'platform_version_release_dates.*',
  resolutions = 'resolutions',
  slug = 'slug',
  sound = 'sound',
  storage = 'storage',
  summary = 'summary',
  url = 'url',
}
