/* tslint:disable */
/* eslint-disable */
/**
 * IGDB API
 * This OpenAPI documentation and schema project IS IN BETA and maintained by [s-crypt.](https://github.com/s-crypt)  The source code and more information is [available in the GitHub repository](https://github.com/s-crypt/IGDB-OpenAPI)  Issues and pull requests are welcome! Please report any bugs or discrepancies you come across! 
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@igdb.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A game\'s operational status   0: released   2: alpha   3: beta   4: early_access   5: offline   6: cancelled   7: rumored   8: delisted   
 * @export
 * @enum {string}
 */

export const GameStatusEnums = {
    /**
    * released
    */
    released: 0,
    /**
    * alpha
    */
    alpha: 2,
    /**
    * beta
    */
    beta: 3,
    /**
    * early_access
    */
    early_access: 4,
    /**
    * offline
    */
    offline: 5,
    /**
    * cancelled
    */
    cancelled: 6,
    /**
    * rumored
    */
    rumored: 7,
    /**
    * delisted
    */
    delisted: 8
} as const;

export type GameStatusEnums = typeof GameStatusEnums[keyof typeof GameStatusEnums];



